// Map company name → domain for Clearbit logo API
const domainMap: Record<string, string> = {
  'google': 'google.com',
  'meta': 'meta.com',
  'amazon': 'amazon.com',
  'apple': 'apple.com',
  'microsoft': 'microsoft.com',
  'netflix': 'netflix.com',
  'uber': 'uber.com',
  'airbnb': 'airbnb.com',
  'linkedin': 'linkedin.com',
  'twitter': 'twitter.com',
  'x': 'x.com',
  'salesforce': 'salesforce.com',
  'oracle': 'oracle.com',
  'adobe': 'adobe.com',
  'paypal': 'paypal.com',
  'stripe': 'stripe.com',
  'shopify': 'shopify.com',
  'spotify': 'spotify.com',
  'snap': 'snap.com',
  'pinterest': 'pinterest.com',
  'lyft': 'lyft.com',
  'dropbox': 'dropbox.com',
  'atlassian': 'atlassian.com',
  'slack': 'slack.com',
  'zoom': 'zoom.us',
  'coinbase': 'coinbase.com',
  'robinhood': 'robinhood.com',
  'databricks': 'databricks.com',
  'snowflake': 'snowflake.com',
  'twilio': 'twilio.com',
  'doordash': 'doordash.com',
  'instacart': 'instacart.com',
  'grubhub': 'grubhub.com',
  'reddit': 'reddit.com',
  'discord': 'discord.com',
  'bytedance': 'bytedance.com',
  'tiktok': 'tiktok.com',
  'baidu': 'baidu.com',
  'alibaba': 'alibaba.com',
  'tencent': 'tencent.com',
  'samsung': 'samsung.com',
  'nvidia': 'nvidia.com',
  'intel': 'intel.com',
  'amd': 'amd.com',
  'qualcomm': 'qualcomm.com',
  'cisco': 'cisco.com',
  'ibm': 'ibm.com',
  'vmware': 'vmware.com',
  'dell': 'dell.com',
  'hp': 'hp.com',
  'hpe': 'hpe.com',
  'mongodb': 'mongodb.com',
  'confluent': 'confluent.io',
  'datadog': 'datadoghq.com',
  'cloudflare': 'cloudflare.com',
  'okta': 'okta.com',
  'palo alto networks': 'paloaltonetworks.com',
  'crowdstrike': 'crowdstrike.com',
  'splunk': 'splunk.com',
  'servicenow': 'servicenow.com',
  'workday': 'workday.com',
  'sap': 'sap.com',
  'infosys': 'infosys.com',
  'tcs': 'tcs.com',
  'wipro': 'wipro.com',
  'cognizant': 'cognizant.com',
  'accenture': 'accenture.com',
  'capgemini': 'capgemini.com',
  'deloitte': 'deloitte.com',
  'pwc': 'pwc.com',
  'ey': 'ey.com',
  'mckinsey': 'mckinsey.com',
  'goldman sachs': 'goldmansachs.com',
  'morgan stanley': 'morganstanley.com',
  'jp morgan': 'jpmorgan.com',
  'j.p. morgan': 'jpmorgan.com',
  'jpmorgan': 'jpmorgan.com',
  'bank of america': 'bankofamerica.com',
  'citigroup': 'citi.com',
  'blackrock': 'blackrock.com',
  'bloomberg': 'bloomberg.com',
  'citadel': 'citadel.com',
  'jane street': 'janestreet.com',
  'two sigma': 'twosigma.com',
  'de shaw': 'deshaw.com',
  'jump trading': 'jumptrading.com',
  'hudson river trading': 'hudsonrivertrading.com',
  'optiver': 'optiver.com',
  'flipkart': 'flipkart.com',
  'paytm': 'paytm.com',
  'phonepe': 'phonepe.com',
  'swiggy': 'swiggy.com',
  'zomato': 'zomato.com',
  'ola cabs': 'olacabs.com',
  'meesho': 'meesho.com',
  'groww': 'groww.in',
  'cred': 'cred.club',
  'razorpay': 'razorpay.com',
  'freshworks': 'freshworks.com',
  'zoho': 'zoho.com',
  'dream11': 'dream11.com',
  'byju\'s': 'byjus.com',
  'udemy': 'udemy.com',
  'coursera': 'coursera.org',
  'duolingo': 'duolingo.com',
  'medium': 'medium.com',
  'grammarly': 'grammarly.com',
  'notion': 'notion.so',
  'asana': 'asana.com',
  'hubspot': 'hubspot.com',
  'intercom': 'intercom.com',
  'zendesk': 'zendesk.com',
  'docusign': 'docusign.com',
  'box': 'box.com',
  'nutanix': 'nutanix.com',
  'pure storage': 'purestorage.com',
  'netapp': 'netapp.com',
  'rubrik': 'rubrik.com',
  'cohesity': 'cohesity.com',
  'commvault': 'commvault.com',
  'veritas': 'veritas.com',
  'expedia': 'expedia.com',
  'booking.com': 'booking.com',
  'airbus se': 'airbus.com',
  'general motors': 'gm.com',
  'tesla': 'tesla.com',
  'waymo': 'waymo.com',
  'cruise': 'getcruise.com',
  'rivian': 'rivian.com',
  'aurora': 'aurora.tech',
  'nuro': 'nuro.ai',
  'disney': 'disney.com',
  'twitch': 'twitch.tv',
  'hulu': 'hulu.com',
  'warner media': 'warnermedia.com',
  'warnermedia': 'warnermedia.com',
  'sony': 'sony.com',
  'roblox': 'roblox.com',
  'unity': 'unity.com',
  'electronic arts': 'ea.com',
  'activision': 'activision.com',
  'blizzard': 'blizzard.com',
  'riot games': 'riotgames.com',
  'epic systems': 'epic.com',
  'wayfair': 'wayfair.com',
  'chewy': 'chewy.com',
  'target': 'target.com',
  'walmart labs': 'walmart.com',
  'lowe\'s': 'lowes.com',
  'autodesk': 'autodesk.com',
  'intuit': 'intuit.com',
  'block': 'block.xyz',
  'square': 'squareup.com',
  'affirm': 'affirm.com',
  'chime': 'chime.com',
  'brex': 'brex.com',
  'plaid': 'plaid.com',
  'capital one': 'capitalone.com',
  'wells fargo': 'wellsfargo.com',
  'american express': 'americanexpress.com',
  'mastercard': 'mastercard.com',
  'visa': 'visa.com',
  'openai': 'openai.com',
  'anthropic': 'anthropic.com',
  'scale ai': 'scale.com',
  'palantir technologies': 'palantir.com',
  'palantir': 'palantir.com',
  'anduril': 'anduril.com',
  'figma': 'figma.com',
  'canva': 'canva.com',
  'wix': 'wix.com',
  'squarespace': 'squarespace.com',
  'godaddy': 'godaddy.com',
  'fiverr': 'fiverr.com',
  'toptal': 'toptal.com',
  'upwork': 'upwork.com',
  'turing': 'turing.com',
};

export function getCompanyDomain(companyName: string): string {
  const key = companyName.toLowerCase().trim();
  return domainMap[key] || `${key.replace(/[^a-z0-9]/g, '')}.com`;
}

export function getCompanyLogo(companyName: string): string {
  const domain = getCompanyDomain(companyName);
  return `https://www.google.com/s2/favicons?domain=${domain}&sz=128`;
}
